# Model parameters
model:
 # General training parameters
  epochs: [100]  # If the model is not hybrid, use this value
  lr: [5.e-3]  # If the model is not hybrid, use this value
  seed: [3110]  # Seed used for training
  t_query_points_n: [20] # number of temperature query points
  kanfov: [3]
  kanstride: [1]
  architecture: ['KANDEMSpectrum']
  log_sploss_factor: [100.0]
  lin_sploss_factor: [100.0]
  # Training, validation, testing and holdout split
  val_months: [[2, 3]]  # Month used for validation
  test_months: [[11, 12]]  # Month used for testing
  holdout_months: [[1, 10]]  # Month used for holdout
  # Linear model architecture
  ln_epochs: [50]  # Linear model epochs
  ln_lr: [1.e-2]  # Linear model Learning rate
  # CNN architecture
  cnn_model: ['efficientnet_b3']  # Choice of CNN model
  cnn_lr: [1.e-4]  # CNN model learning rate
  cnn_dp: [0.75]  # CNN model dropout rate
  cnn_epochs: [50]  # CNN model epochs.
  # wl: # Wavelengths used as input
  "94": [[0]]  
  "131": [[1]]  
  "171": [[2]]  
  "193": [[3]]  
  "211": [[4]]  
  "304": [[5]]  
  "335": [[6]]  
  "1600": [[7]]  
  "1700": [[8]]  
  AIA: [[0, 1, 2, 3, 4, 5, 6, 7, 8]]  
  EUVI: [[2, 3, 4, 5]] 
  EUI: [[2, 5]] 
  SUVI: [[0, 1, 2, 3, 4, 5]]  
  CIRCE: [[1, 3, 5]]
  AIA_UV: [[0, 1, 2, 3, 4, 5, 6]]

  # Training logging
logging: 'spectrum'

wandb:
  entity: 'trilliumtechnologies'  # Name of wandb entity
  project: '2024-SPI3S-Irradiance'  # Name of wandb project
  #group: 'Virtual Instrumentation'  # Name of wandb group
  job_type: 'Irradiance Training'  # Nme of wandb job_type
  tags: ['baseline'] # Run tags
  notes: "Baseline of KandemSpectrum."
  wb_name: "please_delete"
  
